#ifndef SOURCE_STRUTS4EMBEDDED_THREADS_AESHELL_H_
#define SOURCE_STRUTS4EMBEDDED_THREADS_AESHELL_H_
#include "shell.h"

void initAEShell(void);


#endif /* SOURCE_STRUTS4EMBEDDED_THREADS_AESHELL_H_ */
